[features]
seeds = false
skip-lint = false
[programs.devnet]
# esse id é o que o terminal mostrar depois de rodar o comando
# solana address -k target/deploy/myepicproject-keypair.json
myepicproject = "G855bxSdfF5sS3U5rry4TJPh7NKJjhmapWdaKJfCMCT6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/diegosano/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
